language: node_js
node_js:
- '4.0'
- '8.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    skip_cleanup: true
    email: tituswormer@gmail.com
    api_key:
      secure: M8NVYG2YKjA2VaAHzIo6KL+8lidrGqR1XTEBJ4yb49EiBz5ESjwUz9lhWB1OhOO5Z4g7MSqi3TmPkNfv7Y2QNHm+Cw2rfetOfYnmD0q1jcfFZAb0XuZRutFsYJmqswMZLAGs9eROuU/ETA2SwKJvN+k+AB0VHR+JKngzX6RH8tx4geHQ6nxUDkcFxItoLH2QR3enFJ59W7D/H0G2ZeR90B6S60nDoZ0NG1HFC4YNqiQoBaWAs4rP2FGA7ydMbqsc/hBbgz4eakOf4EErwVQ4OZZCM+oEaumS0cqsETzuewwnS+rRwaiJLRuvOqTqTfVSmbnJlmXzHUodpCxfYTP9hYgzqUu+9S1lfNvKbzJs859knSgkrdLA9zwiKaPSmM72+h5crUiNsWJsROmAn6xJrDAuh8QDLIjLdKRWORWoL5smh9nU82Q1hhMgFNYwdNI5JE7bmoC2QXl01HOR+EgwnXhmhZeUU+jGQesVqpunyaNpyp4P1vbw+LtBrFdVEUkaQWGQ+MQ7Ic11ITT6eohIJgcdwyhsENkNLm6uIyCKpRGUZDsXdIhfTI6MxB9FgjxhFs+/0T8fgpcPKSYf5hdWev7ZFdrl9pLZxNEHPG6WZ3CB/WFTbygcm8KQ0EE1cAFi62tZQpIrY683P6NJVdXAHwP4tXbDMDP8bjGkF9NDC4o=
    on:
      tags: true
      node: '4.0'
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: k+DEY/rTQHmcbjcEQrATzQDUcnlGpE8oA6FG6+vMTGve70Dfcx24IzrfOgU0Zwi8XmpBdcUx2wEcOPgPeYUu8ZsTe3yfEuS7wt2OU1qFsyJusem7BBtB3dpXnQbrvOJiI+nYyk7bpRXvdQntO//gtYqVLN5f5P5AR8xMzttfqwiO1zofdgKAIK82tAwLfFY1xGJ/52TJdMAikrhqvoBBEP1sPAluR0JDAAKmOtjyro385CEZKC9Lw3AIAMkfXAvwMqxMinZI5ph2o+0YSzPUZcjd9AXzmEMwaV9XOpxqLcvBBuUt9opP4NNOvYUVwKFOjSfe7M/EoYmjQNChRoasZ09p+UZg63I9VkG4Ooau3xswNcSv5SXwQISD4du75zYAGJNMP/VwVh3D8Dw3T7a9oGNSnQOfGHXK0dGQIosf0FFnNqC6YNE/Vb8dTTx34SaDaDRMW51znDh/NBNk6i3dD4kmO3OyLcVJkNdGLiAJfYx+gbbjLv0v03zWe64G5qUz4xlVQby2QXWREDDPlVvRdu6Yxiyet0fVYP0l4ZIRPnWPV6QRKeHSZmoxFuGAGs7e3iUaUgYWKT8lylCdZUxO30KATlV8AX7IezzWM2nRNTQ8Q6DELr6jI/JY1zdflmeoN9fyG2q8pMgnBIwAQj0wmiEDinng7qEtdu4SXeKwRCw=
    file:
      - "to-vfile.js"
      - "to-vfile.min.js"
    on:
      tags: true
      node: '8.0'
